apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  selector:
    app: flaskappGreen
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30000
