apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-green
  labels:
    app: flaskapp-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp-green
  template:
    metadata:
      labels:
        app: flaskapp-green
    spec:
      containers:
        - name: flaskapp-green
          image: ederd/flaskappgreen:v0.0.1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8000
