apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskappBlue
  labels:
    app: flaskappBlue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskappBlue
  template:
    metadata:
      labels:
        app: flaskappBlue
    spec:
      containers:
        - name: flaskappBlue
          image: ederd/flaskappblue:v0.0.1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  selector:
    app: flaskappBlue
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30000
