apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-blue
  labels:
    app: flaskapp-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp-blue
  template:
    metadata:
      labels:
        app: flaskapp-blue
    spec:
      containers:
        - name: flaskapp-blue
          image: ederd/flaskappblue:v0.0.1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  selector:
    app: flaskapp-blue
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      #nodePort: 30000
