apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: ederd/flaskapp:v0.0.2
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  selector:
    app: flaskapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30000
